BEGIN TRANSACTION;
DROP TABLE IF EXISTS requests2;
CREATE TABLE requests2 (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, method STRING NOT NULL, params STRING, response STRING NOT NULL);
DROP TABLE IF EXISTS requests1;
CREATE TABLE requests1 (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, method STRING NOT NULL, params STRING, response STRING NOT NULL);
DROP TABLE IF EXISTS general;
CREATE TABLE general (current_set STRING, start_set DATE, end_set DATE, login STRING, password STRING, version INTEGER, last_login DATE, last_sync DATE, font_size INTEGER);
DROP TABLE IF EXISTS responces;
CREATE TABLE responces (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, method STRING NOT NULL, key_params STRING, params STRING, data_name STRING, data_file STRING, data_type STING, data_raw BLOB);
COMMIT TRANSACTION;

